version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - ./.env
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq
    hostname: ${RABBITMQ_HOST}

volumes:
  rabbitmq_data: {}

